name = "Bimbo Mafiacraft"
author = "beckkake"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2621e307060bce8ea885595b371bb26311da1e133c3bc823b32761cb098e5754"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
