name = "Bimbo Mafiacraft"
author = "beckkake"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "569bb84329763d957e20230e507289091db154823d91eb7d4c985b087b31698f"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
