name = "Bimbo Mafiacraft"
author = "beckkake"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5bdf4ea340c24400dd614981632bbd31690639ebc171f83d4c43ef021e7e7bdd"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.113"
