name = "Bimbo Mafiacraft"
author = "beckkake"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ba6f24dc060fb1beaafa3b2d0be4db45284aa5e93d4c65a08de9bf8f5ac88ab"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
