name = "Bimbo Mafiacraft"
author = "beckkake"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "522e94b2203491beac69b6b5ddea288e517d110ec71e89fb7b18d46db4765a10"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.113"
