name = "Bimbo Mafiacraft"
author = "beckkake"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4247d187ee97162d68255ae91115d77b0df7d02d76aebefca57ad86625fa224c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.113"
