name = "Bimbo Mafiacraft"
author = "beckkake"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d56412b564168b954c964fc4ed564b2761fc8395c4508084e512138bbb54b3f9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.113"
