name = "Bimbo Mafiacraft"
author = "beckkake"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b12ca20fc2754ad5debfebee6d1267898cd7148c2f137c251fdaa20dcdff2cc4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.113"
