name = "Bimbo Mafiacraft"
author = "beckkake"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66b96a1edabe00fec47cf5647c73c5ee81d7684e69d336aec71ee5206be1aa8d"

[versions]
fabric = "0.16.14"
minecraft = "1.20.1"
